# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 131f8f7af8f2eef996a62027faf008dab4095b11a23ba3a5bd4f0db10e450d65736a2e01a45975d62fb8416687cd1965701fb66517001aaca4e384d48c8adb65

test:
  secret_key_base: 9d0cdfef26d398fca48b51f9cfeafd752644ee1fd3933e9e6e47d8e89af2b4ef2c66dc9a27d905f031198056187d95e33cd20c2c00157e06a8984a370a990026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
